apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: example-cluster
spec:
  replicas: 1
  image: ghcr.io/oracle/coherence-ce:22.06
  application:
    main: com.tangosol.net.DefaultCacheServer
  volumeMounts:
    - name: cache-jar
      mountPath: /coherence/ext
  volumes:
    - name: cache-jar
      emptyDir: {}

  containers:
    - name: jar-injector
      image: busybox
      command: ["sh", "-c", "cp /input/my-cache.jar /output/ && sleep 3600"]
      volumeMounts:
        - name: cache-jar
          mountPath: /output
        - name: jar-source
          mountPath: /input

  volumeClaimTemplates:
    - metadata:
        name: jar-source
      spec:
        accessModes: ["ReadOnlyMany"]
        resources:
          requests:
            storage: 1Gi
